### ISSUE TITLE
Pull Requestができません

### ISSUE THREAD

**Issue by Ryb7532** [prg1-2018/assignment1#17]
Pull Requestしようと思っても、”Checking mergeability… Don’t worry, you can still create the pull request. ”と出てきてcreate pull requestできません。branchに差異が生じてるのかと思い、merge等しても見ましたが状況に変化はありませんでした。どうすればいいでしょうか。

**Comment by Ryb7532** [comment]
google chromeでpull requestしたらできました。

**Comment by ryuhei-mori** [comment]
よく分かりませんが、そのようなメッセージが表示されているのであれば　pull request できるのではないでしょうか。

**Comment by Ryb7532** [comment]
create pull requestを押しても反応がなく、何度か試して見ましたが一向にできなかったので質問しました。”Can't automatically merge”ではなかったので自分もできるとは思いましたができませんでした。
